### ISSUE TITLE
share code

### ISSUE THREAD

**Issue by tungvuong** [satrancci/web-crawler-with-proxies#37]
Hi Alex, your work is excellent. I am a doctoral researcher at the University of Helsinki (https://researchportal.helsinki.fi/en/persons/thanh-tung-vuong). My research would require an implementation of a simple search system. For instance, the system would crawl and index content from some health and medical sites for a conversational agent. Because of such a purpose, would you be so kind to share the code?

**Comment by satrancci** [comment]
Hi Thanh, thank you for the feedback and nice to meet you! Actually the code has been public all along :) Please refer to 
[https://github.com/satrancci/web-crawler-with-proxies/tree/b54aa1e824a3919291d01e0a6ad6c318412170b5](https://github.com/satrancci/web-crawler-with-proxies/tree/b54aa1e824a3919291d01e0a6ad6c318412170b5). This is one commit before head in which I updated .gitignore.

Please let me know if you have any further questions.

Thanks,
Alex

**Comment by tungvuong** [comment]
Hi Alex,

Hopefully, this message could reach you. Github does not allow to send a private message.
Thanks a lot for your code.
In case the work gets published. I would like to give acknowledgement to you.

Best regards,
Vuong
